import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
df = pd.read_csv("C:\\Users\\Admin\\Downloads\\data4.csv")
series = df['Value']
plt.figure(figsize=(8,4))
plt.plot(series)
plt.title("Original Time Series")
plt.xlabel("Time")
plt.ylabel("Value")
plt.grid(True)
plt.show()
df['Log_Value'] = np.log(series)
plt.figure(figsize=(8,4))
plt.plot(df['Log_Value'])
plt.title("Log Transformed Time Series")
plt.xlabel("Time")
plt.ylabel("Log(Value)")
plt.grid(True)
plt.show()
df['Diff_Value'] = df['Log_Value'].diff()
plt.figure(figsize=(8,4))
plt.plot(df['Diff_Value'])
plt.title("Differenced Time Series")
plt.xlabel("Time")
plt.ylabel("Difference")
plt.grid(True)
plt.show()
df['Moving_Average'] = series.rolling(window=3).mean()
plt.figure(figsize=(8,4))
plt.plot(series, label="Original")
plt.plot(df['Moving_Average'], label="3-Point Moving Average")
plt.title("Moving Average")
plt.xlabel("Time")
plt.ylabel("Value")
plt.legend()
plt.grid(True)
plt.show()
df = df.dropna()
df['Time'] = np.arange(len(df))
X = df[['Time']]
y = df['Log_Value']
model = LinearRegression()
model.fit(X, y)
df['Predicted_Log'] = model.predict(X)
df['Predicted'] = np.exp(df['Predicted_Log'])
plt.figure(figsize=(8,4))
plt.plot(df.index, np.exp(df['Log_Value']), label="Actual")
plt.plot(df.index, df['Predicted'], linestyle='--', label="Predicted")
plt.title("Actual vs Predicted")
plt.xlabel("Time")
plt.ylabel("Value")
plt.legend()
plt.grid(True)
plt.show()
rmse = np.sqrt(mean_squared_error(np.exp(df['Log_Value']), df['Predicted']))
mae = mean_absolute_error(np.exp(df['Log_Value']), df['Predicted'])
print("RMSE :", rmse)
print("MAE  :", mae)
